# Generated by Django 4.2.11 on 2024-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('household_size', models.IntegerField()),
                ('diet_type', models.CharField(choices=[('plant-based', 'Plant-based'), ('vegetarian', 'Vegetarian'), ('high-meat', 'High-meat')], max_length=50)),
                ('car_travel_km', models.FloatField()),
                ('public_transport_mode', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train')], max_length=50)),
                ('public_transport_distance', models.FloatField()),
                ('electricity_kwh', models.FloatField()),
                ('heating_type', models.CharField(choices=[('natural-gas', 'Natural Gas'), ('oil', 'Oil'), ('electric', 'Electric')], max_length=50)),
                ('heating_usage', models.FloatField()),
                ('non_recyclable_waste_kg', models.FloatField()),
                ('recyclable_waste_kg', models.FloatField()),
                ('water_usage_m3', models.FloatField()),
                ('meat_dairy_eggs_kg', models.FloatField()),
                ('fruits_vegetables_kg', models.FloatField()),
            ],
        ),
    ]
