# Generated by Django 4.2.11 on 2024-04-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_carbonfootprintrecord_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbonfootprintrecord',
            options={'ordering': ['-date_recorded']},
        ),
    ]
