# Generated by Django 4.2.11 on 2024-04-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_carbonfootprintrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbonfootprintrecord',
            options={},
        ),
        migrations.AddField(
            model_name='carbonfootprintrecord',
            name='meat_type',
            field=models.CharField(blank=True, choices=[('beef', 'Beef'), ('chicken', 'Chicken')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carbonfootprintrecord',
            name='total_footprint',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
