# Generated by Django 4.2.11 on 2024-04-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCarbonFootprintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_footprint', models.FloatField(blank=True, editable=False, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.profile')),
            ],
        ),
    ]
