# Generated by Django 4.2.11 on 2024-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_postcarbonfootprintrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='footprint_goal',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
