# Generated by Django 4.2.11 on 2024-04-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_profile_footprint_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='carbonfootprintrecord',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.DeleteModel(
            name='PostCarbonFootprintRecord',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
