# Generated by Django 4.2.11 on 2024-04-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprintrecord',
            name='grade',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
