# Generated by Django 4.2.15 on 2025-04-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carbonfootprintrecord",
            name="user",
        ),
    ]
